name: Asset & Data Validation

on:
  push:
    branches:
      - main
      - 'feature/*'
      - 'bugfix/*'
  pull_request:
    branches:
      - main

jobs:
  validate_icons:
    name: Validate Icons
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow

    - name: Run icon validation script
      run: python .github/scripts/validate_icons.py
  
  validate_categories:
    name: Validate Categories
    runs-on: ubuntu-latest
    needs: validate_icons

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run category validation script
      run: python .github/scripts/validate_categories.py

  validate_ingredients:
    name: Validate Ingredients
    runs-on: ubuntu-latest
    needs: validate_categories

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run ingredient validation script
      run: python .github/scripts/validate_ingredients.py
